continent_country_dict = {
	"asia":["Afghanistan","Armenia","Azerbaijan","Bahrain","Bangladesh","Bhutan","Brunei","Burma","Cambodia","China","Christmas Island","Cocos (Keeling) Islands","Cyprus","Gaza Strip","Hong Kong","India","Indonesia","Iran","Iraq","Israel","Japan","Jordan","Kazakhstan","Korea, North","Korea, South","Kuwait","Kyrgyzstan","Laos","Lebanon","Macau","Malaysia","Maldives","Mongolia","Nepal","Oman","Pakistan","Philippines","Qatar","Saudi Arabia","Singapore","Sri Lanka","Syria","Taiwan","Tajikistan","Thailand","Turkmenistan","United Arab Emirates","Uzbekistan","Vietnam","West Bank","Yemen",],

	"europe":["Albania","Austria","Belarus","Belgium","Bosnia and Herzegovina","Bulgaria","Croatia","Czeck Republic","Estonia","Faroe Islands", "Finland","France","Georgia","Germany","Gibraltar","Greece","Guernsey","Holy See (Vatican City)","Hungary","Iceland","Ireland","Northern Ireland","Italy","Jersey","Latvia","Liechtenstein","Lithuania","Luxembourg","Macedonia, Former Yugoslav Republic of","Malta","Man, Isle of","Moldova","Monaco","Netherlands","Norway","Poland","Portugal","Romainia","Russia","San Marino","Scotland","Slovakia","Slovenia","Spain","Sweden","Switzerland","Turkey","Ukraine","United Kingdom","Yugoslavia",],

	"australia":["Ashmore and Cartier Island","Australia","Denmark","Guinea","Kiribati","Wales",],

	"africa":["Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon","Cape Verde","Central African Republic","Chad","Congo, Democratic Republic of the","Congo, Republic of the","Cote d'Ivoire","Djibouti","Egypt","Equatorial Guinea","Eritrea","Ethiopia","Gabon","Gambia, The","Ghana","Guinea-Bissau","Kenya","Lesotho","Liberia","Libya","Madagascar","Malawi","Mali","Mauritania","Mauritius","Mayotte","Morocco","Mozambique","Namibia","Niger","Nigeria","Reunion","Rwanda","Saint Helena","Sao Tome and Principe","Senegal","Seychelles","Sierra Leone","Somalia","South Africa","Sudan","Swaziland","Tanzania","Tunisia","Uganda","Western Sahara","Zambia","Zimbabwe"],

	"america":["American Samoa","Anguilla","Antigua and Barbuda","Argentina","Aruba","Bahamas","Barbados","Belize","Bermuda","Bolivia","Brazil","British Virgin Islands","Canada","Cayman Islands","Chile","Clipperton Island","Colombia","Comoros","Costa Rica","Cuba","Dominica","Dominican Republic","Ecuador","El Salvador","Falkland Islands (Islas Malvinas)","French Guiana","Greenland","Grenada","Guadeloupe","Guatemala","Guyana","Haiti","Honduras","Jamaica","Martinique","Mexico","Montserrat","Netherlands Antilles","Nicaragua","Panama","Paraguay","Peru","Puerto Rico","Saint Kitts and Nevis","Saint Lucia","Saint Pierre and Miquelon","Saint Vincent and the Grenadines","Suriname","Tobago","Trinidad","Uruguay","USA","Venezuela","Virgin Islands",]
}